before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: aliuy1tDjvl8iFKeYBiAHN8HoA/1dLlz1o8ve3kwv/6AP1B4JTwCdP6vMfVg27537o2RMwx+Qu7260L2ffn3+Z/i8go6qsx7kI1bS4k7xsX5rivKE30Dlij30T5XqeOb4aFBdmePRjEDpjMx6bxy6j2AP7UnhfmIty87LpDF/15skhmIwBwpsasSgiE+iUZY7ZVcHVhQHGC+7ybxQLe20d9SRazjYDl/jdzMQJQuteSL04wcOVq5vuHCCjBUHxp3DTGjIasc+DqDG7k4+cDlCPSs3/nZEVDVJ3mzJ6tpEaM3uo9tC9g47AomBm+qwLxbdVlyzXkg6IkOLuosFlUggMF1XVpIsDXcgjtj7FrIoElA/ydPUlzW40p+O+pqx+VogTgUa94zSl9hkV3cUr36lQbHN0lmsjdVE5uTGOOcEnEK4L5i5v3MUbAvO0ONsYKNVXBspAcJIEkedvkp7qR/lFjmUDxDbYLe7P/38DMWxwXY59KvxeYZjlyUwqPshzL7SGd/VbpdLUvSpwWve8XHlBlm9UQCac5fDZvab1tpK6VQA2h5OGXALATl/kBZP4IaMN0lK2A2JU+5w679DtgLk3F3c59hUAB+8SdYeK7FgBRqNeUv3yTjIAS0PbsA2BpjrxQMY9zjhI4rGZANJvV8PN58n8vUCqeJoFvP6TDwSzw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
